### ISSUE TITLE
Updates to consider.

### ISSUE THREAD

**Issue by kylebrowning** [PikLips/D8iOS#16]
Hey, this is a great imeplementation. 

Im wondering if we could do the same in the demo app of the new Swift version and use the new API's in the new SDK, [(waterwheel-swift)](https://github.com/acquia/waterwheel-swift)

**Comment by littleM** [comment]
I will check it out.

**Comment by PikLips** [comment]
Kyle,

I have been away from this for a while.  Sorry for the delay.  I am looking at updating this for iOS 11 but am not ready for swift.  That may change, depending on partners.  However, a lot will depend on your libraries.  What is your feeling about thier support of Objective-C going forward?

**Comment by kylebrowning** [comment]
Ahh yeah, I am no longer supporting Objective-C. Swift is the future!

**Comment by PikLips** [comment]
Okay, good to know. Thanks!
